baseurl = "http://www.normansicily.org/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
title = "The Norman Sicily Project"
theme = "hamburg"

[params]
    title = "The Norman Sicily Project"
    subtitle = "Documenting Sicily's First Kingdom, 1061-1194"
    # Short subtitle/tagline. This is displayed in the header.
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
    # To load additional CSS styles
    customCSS = ['custom.css']
    # Show this very user-friendly and absolutely not annoying GDPR notice at the bottom of the page
    ShowGDPRNotice = true
    # Since 0.57.0 there's the concept of "main sections". The files for the section "posts" are in "./content/posts/".
    mainSections = ["posts"]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    ga_api_key = "UA-75482271-1"
    twitter = "Norman_Sicily"
    github = "the-norman-sicily-project"
    facebook = "TheNormanSicilyProject"
    instagram = "thenormansicilyproject"

[languages]
    [languages.en]
        languageCode = "en"
        languageName = "English"
        # Copyright notice. This is displayed in the footer.
        copyright = "&copy;  2015 - 2020 by Dawn Marie Hayes and Joseph Hayes. All Rights Reserved."
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "HOME"
                identifier = "HOME"
                url = "home"
                weight = 9
            [[languages.en.menu.main]]
                name = "PEOPLE"
                identifier = "PEOPLE"
                url = "people"
                weight = 6
            [[languages.en.menu.main]]
                name = "PLACES"
                identifier = "PLACES"
                url = "places"
                weight = 5
            [[languages.en.menu.main]]
                name = "RESOURCES"
                identifier = "RESOURCES"
                url = "resources"
                weight = 3
            [[languages.en.menu.main]]
                name = "BLOG"
                identifier = "BLOG"
                url = "posts"
                weight = 4
            [[languages.en.menu.main]]
                name = "CONTACT US"
                identifier = "ContactUs"
                url = "contactus"
                weight = 1
